name: Auto update master from release

on:
  push:
    branches:
      - release

jobs:
  autoupdate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch_depth: 0

      - run: git checkout -b R-$GITHUB_SHA

      - uses: actions/checkout@v2
        with:
          fetch_depth: 0
          ref: master

      - run: git checkout -b R2M-$GITHUB_SHA

      - run: git merge R-$GITHUB_SHA
      - run: git push origin R2M-$GITHUB_SHA
